//go:build !debug

/**
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

// Code generated by trace-gen-functions tool. DO NOT EDIT.

package database

import (
	"context"

	typesv2 "github.com/adobe/aquarium-fish/lib/types/aquarium/v2"
)

func (d *Database) SubscribeApplicationTask(ctx context.Context, ch chan ApplicationTaskSubscriptionEvent) {
	d.subscribeApplicationTaskImpl(ctx, ch)
}

func (d *Database) UnsubscribeApplicationTask(ctx context.Context, ch chan ApplicationTaskSubscriptionEvent) {
	d.unsubscribeApplicationTaskImpl(ctx, ch)
}

func (d *Database) ApplicationTaskList(ctx context.Context) ([]typesv2.ApplicationTask, error) {
	return d.applicationTaskListImpl(ctx)
}

func (d *Database) ApplicationTaskListByApplication(ctx context.Context, appUID typesv2.ApplicationUID) ([]typesv2.ApplicationTask, error) {
	return d.applicationTaskListByApplicationImpl(ctx, appUID)
}

func (d *Database) ApplicationTaskCreate(ctx context.Context, at *typesv2.ApplicationTask) error {
	return d.applicationTaskCreateImpl(ctx, at)
}

func (d *Database) ApplicationTaskSave(ctx context.Context, at *typesv2.ApplicationTask) error {
	return d.applicationTaskSaveImpl(ctx, at)
}

func (d *Database) ApplicationTaskGet(ctx context.Context, uid typesv2.ApplicationTaskUID) (*typesv2.ApplicationTask, error) {
	return d.applicationTaskGetImpl(ctx, uid)
}

func (d *Database) ApplicationTaskDelete(ctx context.Context, uid typesv2.ApplicationTaskUID) error {
	return d.applicationTaskDeleteImpl(ctx, uid)
}

func (d *Database) ApplicationTaskListByApplicationAndWhen(ctx context.Context, appUID typesv2.ApplicationUID, when typesv2.ApplicationState_Status) ([]typesv2.ApplicationTask, error) {
	return d.applicationTaskListByApplicationAndWhenImpl(ctx, appUID, when)
}
