//go:build !debug

/**
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

// Code generated by trace-gen-functions tool. DO NOT EDIT.

package database

import (
	"context"

	typesv2 "github.com/adobe/aquarium-fish/lib/types/aquarium/v2"
)

func (d *Database) RoleList(ctx context.Context) ([]typesv2.Role, error) {
	return d.roleListImpl(ctx)
}

func (d *Database) RoleGet(ctx context.Context, name string) (*typesv2.Role, error) {
	return d.roleGetImpl(ctx, name)
}

func (d *Database) RoleCreate(ctx context.Context, r *typesv2.Role) error {
	return d.roleCreateImpl(ctx, r)
}

func (d *Database) RoleSave(ctx context.Context, r *typesv2.Role) error {
	return d.roleSaveImpl(ctx, r)
}

func (d *Database) RoleDelete(ctx context.Context, name string) error {
	return d.roleDeleteImpl(ctx, name)
}
