/**
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

// Code generated by Aquarium buf-gen-pb-data. DO NOT EDIT.

package aquariumv2

import (
	pbTypes "github.com/adobe/aquarium-fish/lib/rpc/proto/aquarium/v2"
)

// StreamError is a data for StreamError without internal locks
type StreamError struct {
	Code    string `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}

// FromStreamError creates a StreamError from StreamError
func FromStreamError(src *pbTypes.StreamError) StreamError {
	if src == nil {
		return StreamError{}
	}

	result := StreamError{}
	result.Code = src.GetCode()
	result.Message = src.GetMessage()
	return result
}

// ToStreamError converts StreamError to StreamError
func (s StreamError) ToStreamError() *pbTypes.StreamError {
	result := &pbTypes.StreamError{}

	result.Code = s.Code
	result.Message = s.Message
	return result
}
