# Example Fish configuration with OpenTelemetry monitoring enabled
# This configuration shows how to enable comprehensive monitoring

# Basic Fish configuration
directory: "fish_data"
api_address: "0.0.0.0:8001"
node_address: "127.0.0.1:8001"
node_name: "fish-node-1"
node_location: "datacenter-1"

# OpenTelemetry monitoring configuration
monitoring:
  enabled: true

  # OTLP endpoints for traces, metrics, and logs
  # These point to the grafana/otel-lgtm container
  otlp_endpoint: "localhost:4317"

  # Pyroscope endpoint for continuous profiling
  pyroscope_url: "http://localhost:4040"

  # Service identification
  service_name: "aquarium-fish"
  service_version: "1.0.0"
  node_name: "fish-node-1"
  node_location: "datacenter-1"

  # Sampling configuration
  sample_rate: 1.0  # 100% sampling for development, reduce for production

  # Metrics collection interval
  metrics_interval: "15s"

  # Feature toggles
  enable_tracing: true
  enable_metrics: true
  enable_logs: false      # Temporarily disabled due to build issues
  enable_profiling: true

# TLS configuration
tls_ca_crt: "ca.crt"
tls_key: "fish-node-1.key"
tls_crt: "fish-node-1.crt"

# Database settings
db_cleanup_interval: "10m"
db_compact_interval: "1h"

# Resource limits
cpu_limit: 4
mem_target: "2GB"
node_slots_limit: 10

# Allocation settings
allocation_retry: 3
elected_rounds_to_wait: 10
default_resource_lifetime: "24h"

# Disable authentication for testing (not recommended for production)
disable_auth: false

# Driver configurations
drivers:
  # Example AWS driver configuration
  aws:
    region: "us-west-2"
    # Add your AWS-specific settings here

  # Example Docker driver configuration
  docker:
    # Add your Docker-specific settings here

  # Example native driver configuration
  native:
    # Add your native-specific settings here
