/**
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

// Code generated by Aquarium buf-gen-permissions. DO NOT EDIT.

package auth

// Service and Method constants
const (
	// ApplicationResourceAccessService service constants
	ApplicationResourceAccessService       = "ApplicationResourceAccessService"
	ApplicationResourceAccessServiceAccess = "ApplicationResourceAccessServiceAccess"

	// ApplicationService service constants
	ApplicationServiceDeallocateAll  = "ApplicationServiceDeallocateAll"
	ApplicationServiceGetResourceAll = "ApplicationServiceGetResourceAll"
	ApplicationServiceGetStateAll    = "ApplicationServiceGetStateAll"
	ApplicationServiceGetAll         = "ApplicationServiceGetAll"
	ApplicationServiceListAll        = "ApplicationServiceListAll"

	// ApplicationTaskService service constants
	ApplicationTaskService       = "ApplicationTaskService"
	ApplicationTaskServiceGet    = "ApplicationTaskServiceGet"
	ApplicationTaskServiceGetAll = "ApplicationTaskServiceGetAll"

	// LabelService service constants

	// NodeService service constants

	// RoleService service constants

	// ServiceMappingService service constants
	ServiceMappingService       = "ServiceMappingService"
	ServiceMappingServiceGet    = "ServiceMappingServiceGet"
	ServiceMappingServiceDelete = "ServiceMappingServiceDelete"
	ServiceMappingServiceList   = "ServiceMappingServiceList"
	ServiceMappingServiceCreate = "ServiceMappingServiceCreate"

	// UserService service constants
	UserServiceListAll   = "UserServiceListAll"
	UserServiceUpdateAll = "UserServiceUpdateAll"
	UserServiceGetAll    = "UserServiceGetAll"

	// VoteService service constants
	VoteService        = "VoteService"
	VoteServiceList    = "VoteServiceList"
	VoteServiceListAll = "VoteServiceListAll"
)
