name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # To get all the tags for versioning

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build
        run: RELEASE=1 ./build.sh

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: aquarium-fish*.tar.xz

      - name: Test
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          name="$(ls aquarium-fish-*.linux_amd64)"
          FISH_PATH="$PWD/$name" go test -v -failfast -parallel 4 -count=1 ./tests/... 2>&1 | go-junit-report -iocopy -set-exit-code -out report.xml

      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: report.xml
