name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CodeQL:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: ./build-linux.sh

    - name: Test
      run: |
        go install github.com/jstemmer/go-junit-report/v2@latest
        FISH_PATH=$PWD/aquarium-fish.linux_amd64 go test -failfast -parallel 4 -count=1 ./tests/... | go-junit-report -iocopy -set-exit-code -out report.xml

    - name: Test Summary
      uses: test-summary/action@v1
      if: always()
      with:
        paths: report.xml
