name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CodeQL:
    name: CodeQL validation
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  GolangCI:
    runs-on: ubuntu-latest
    name: Code Lint
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow write access to checks to allow the action to annotate code in the PR.
      checks: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Generate code
        run: ONLYGEN=1 ./build.sh

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To get all the tags for versioning

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: RELEASE=1 ./build.sh

      - name: Checking no files in git were changed during the build
        run: |
          if [ "x$(git status -s)" != 'x' ]; then
            echo 'Build modified the workspace, please fix or add to gitignore list:'
            git status
            exit 1
          fi

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: aquarium-fish*.tar.xz
  
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To get all the tags for versioning

      - name: Unpack built binaries
        run: |
          tar xf aquarium-fish*.linux_amd64.tar.xz

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # Build here is needed to prepare a debug race instrumented version of the binary
      - name: Build
        run: RELEASE=1 ./build.sh

      - name: Integration Tests
        run: |
          go install github.com/jstemmer/go-junit-report/v2@85bf471  # Oct 18, 2023
          FISH_PATH="$PWD/$(ls -t aquarium-fish*.linux_amd64 | head -1)" go test -v -parallel 4 -count=1 -skip '_stress$' ./tests/... 2>&1 | go-junit-report -iocopy -set-exit-code -out report.xml

      - name: Benchmarks main
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        if: github.ref == 'refs/heads/main'
        env:
          INPUT_PUBLISH: true
          INPUT_CHECKS: true
          INPUT_PRUNE_COUNT: 30
          INPUT_GO_TEST_FLAGS: "-run=^# -cpu 1,2 -benchmem"
          INPUT_CHECKS_CONFIG: gobenchdata-checks.yml
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Benchmarks PR
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        if: github.ref != 'refs/heads/main'
        env:
          INPUT_PUBLISH: false
          INPUT_CHECKS: true
          INPUT_PRUNE_COUNT: 30
          INPUT_GO_TEST_FLAGS: "-run=^# -cpu 1,2 -benchmem"
          INPUT_CHECKS_CONFIG: gobenchdata-checks.yml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests
          path: |
            /tmp/gobenchdata/*
            report.xml

      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: report.xml
