---
name: Handle Release

on:
  release:
    types: [ "created" ]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To get all the tags for versioning

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: RELEASE=1 ./build.sh

      - name: Upload the artifacts
        uses: AButler/upload-release-assets@3d6774fae0ed91407dc5ae29d576b166536d1777  # Nov 20, 2023 - v3.0
        with:
          files: 'aquarium-fish*.tar.xz;aquarium-fish*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  Release-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To get all the tags for versioning

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: zulu

      - name: Set version from the closest git tag
        run: |
          cd java
          mvn --batch-mode versions:set -DnewVersion="$(git describe --always --tags --match 'v*' | sed 's/^v//')$([ "$(git diff)" = '' ] || echo '-dirty')"

      - name: Build
        run: |
          cd java
          mvn --batch-mode --update-snapshots package

      - name: Upload the artifacts
        uses: AButler/upload-release-assets@3d6774fae0ed91407dc5ae29d576b166536d1777  # Nov 20, 2023 - v3.0
        with:
          files: java/target/aquarium-fish-java-*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
